name: Build Box64 for Android ARM64

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: Configure CMake
        run: |
          mkdir build && cd build # Create build directory and cd into it
          export BOX64_COMPILER=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang
          cmake .. -DCMAKE_C_COMPILER=${BOX64_COMPILER} -DTERMUX=0 -DANDROID=1 -DARM_DYNAREC=1 -DBAD_SIGNAL=1 -DCMAKE_BUILD_TYPE=Release -DHAVE_TRACE=0 -DZYDIS3=0 -DSTATICBUILD=0 -DBOX32=0 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCI=false

      - name: Build
        run: |
          cd build
          make -j$(nproc)

      - name: Package WCP for Winlator
        run: |
          mkdir -p wcp_package/usr/bin
          cp build/box64 wcp_package/usr/bin/box64
          cd wcp_package
          zip -r ../box64-upgraded.wcp .

      - name: Upload raw binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: box64-arm64-android
          path: build/box64

      - name: Upload WCP artifact
        uses: actions/upload-artifact@v4
        with:
          name: box64-upgraded-wcp
          path: box64-upgraded.wcp
